### ISSUE TITLE
你的评论系统寄了

### ISSUE THREAD

**Issue by struggle-upwards** [thun888/myblog#94]
![image](https://github.com/user-attachments/assets/1148ad13-13c9-44dd-bddf-66592b19c17a)

**Comment by thun888** [comment]
是Artalk的问题，输入emoji就会报错，我去反馈一下。友链等会给你加上😺
![image](https://github.com/user-attachments/assets/df7f4530-a1e3-412d-a6d5-a28a0c618f27)

```
2024/10/02 22:01:11.647 [31mERROR[0m [handler/comment_create.go:142] Save Comment error: Error 1366 (HY000): Incorrect string value: '\xF0\x9F\x98\x80' for column 'content' at row 1
```
